name: Knit README.Rmd

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  knit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"))'
      - name: Knit README.Rmd
        run: |
          knitr::knit('README.Rmd')
