name: ChatGPT Test - Knit README.Rmd
on:
  push:
    branches:
      - main
    paths:
      - '**.Rmd'
  schedule:
    - cron: '0 8 * * *' # run at 8am every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'
    - name: Install Dependencies
      run: |
        install.packages("rmarkdown")
        install.packages("knitr")
    - name: Knit R Markdown
      if: ${{ github.event_name == 'push' || inputs.force_run == 'true' }}
      run: |
        Rscript -e 'rmarkdown::render("https://raw.githubusercontent.com/spsanderson/package-downloads/master/README.Rmd")'
    - name: Notify Success
      if: ${{ always() }}
      run: echo "Knitting complete."
    - name: Notify Failure
      if: ${{ failure() }}
      run: echo "Knitting failed."
    inputs:
      force_run:
        description: 'Set to "true" to force a run of the workflow'
        default: 'false'
