name: test-render-rmarkdown

on:
  schedule:  
    - cron:  '0 08 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render-rmarkdown:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Render Rmarkdown
        run: bash ./bash/data_refresh.sh
